Repository ouzi-dev/whalers-of-the-moon, pull requests merged in 2019-11, with the labels that each got.

#12 feat: add gotpl, terraform, aws cli
  Makefile
  toolbox/Dockerfile
  toolbox/Makefile
Labels: approved, lgtm, size/M

#13 feat: add jq
  toolbox/Dockerfile
  toolbox/Makefile
Labels: approved, lgtm, size/XS

#14 feat: add credstash to toolbox
  toolbox/Dockerfile
  toolbox/Makefile
Labels: approved, lgtm, size/S

#15 fix: add missing ssl lib
  toolbox/Dockerfile
  toolbox/Makefile
Labels: approved, lgtm, size/XS

#16 feat: add gcloud cli
  toolbox/Dockerfile
  toolbox/Makefile
Labels: approved, lgtm, size/S

#17 feat: bump helm kubectl awscli and gcloud versions
  toolbox/Makefile
Labels: approved, lgtm, size/S

#19 feat: update terraform
  toolbox/Makefile
Labels: approved, lgtm, size/XS
