Repository ouzi-dev/whalers-of-the-moon, pull requests merged in 2019-10, with the labels that each got.

#3 feature: updated golang version and linter
  README.md
  go-builder/Dockerfile
  go-builder/Makefile
Labels: approved, lgtm, size/S, ¯\_(ツ)_/¯

#4 fix: add ssh to go builder to be able to use git clone with ssh
  go-builder/Dockerfile
Labels: approved, lgtm, size/XS

#5 Add helm images
  Makefile
  helm/Dockerfile
  helm/Makefile
Labels: approved, lgtm, size/M

#6 fix: do not remove build dependencies when building the helm image
  helm/Dockerfile
Labels: approved, lgtm, size/XS

#7 feat: add new toolbox image
  Makefile
  README.md
  helm/Dockerfile
  helm/Makefile
  toolbox/Dockerfile
  toolbox/Makefile
Labels: approved, lgtm, size/L

#8 fix: use helm 2
  toolbox/Makefile
Labels: approved, lgtm, size/XS

#9 fix: switch back to helm 3
  toolbox/Makefile
Labels: approved, lgtm, size/XS

#10 feat: added kubectl to toolbox
  README.md
  toolbox/Dockerfile
  toolbox/Makefile
Labels: approved, lgtm, size/S
