Repository ouzi-dev/whalers-of-the-moon, pull requests merged in 2020-02, with the labels that each got.

#24 feat: update the versions of the go-builder and toolbox packages
  go-builder/Makefile
  toolbox/Makefile
Labels: approved, lgtm, size/S

#25 feat: add node and npm to dind image
  kube-dind/Dockerfile
  kube-dind/Makefile
Labels: approved, lgtm, size/S

#26 feat: add git secret scanner
  Makefile
  README.md
  git-secret-scanner/Dockerfile
  git-secret-scanner/Makefile
Labels: approved, lgtm, size/M

#27 feat: add new python builder image
  .prow.yaml
  Makefile
  python-builder/Dockerfile
  python-builder/Makefile
Labels: approved, lgtm, size/L

#28 feat: move to python3
  python-builder/Makefile
Labels: approved, lgtm, size/XS

#29 feat: use go 1.13.8 and golanci-lint 1.23.6
  .prow.yaml
  README.md
  go-builder/Dockerfile
  go-builder/Makefile
Labels: approved, lgtm, size/M

#30 fix: update toolbox and build on PR and push on merge to master
  .prow.yaml
  README.md
  toolbox/Makefile
Labels: approved, lgtm, size/L

#31 fix: update helm
  README.md
  helm/Dockerfile
  helm/Makefile
Labels: approved, lgtm, size/S

#32 fix: updated helm in toolbox
  README.md
  toolbox/Dockerfile
  toolbox/Makefile
Labels: approved, lgtm, size/M
