Repository ouzi-dev/whalers-of-the-moon, pull requests merged in 2020-03, with the labels that each got.

#33 feat: add extra python dependencies to the builder image
  python-builder/Dockerfile
Labels: approved, lgtm, size/XS

#34 fix: Do not build the kube dind image every time
  .prow.yaml
Labels: approved, lgtm, size/XS

#35 feat: add yq
  toolbox/Dockerfile
  toolbox/Makefile
Labels: approved, lgtm, size/XS

#36 feat: bump tf to 0.12.21
  toolbox/Makefile
Labels: approved, lgtm, size/XS

#37 fix: update go to 1.14.0
  README.md
  go-builder/Makefile
  toolbox/Makefile
Labels: approved, lgtm, size/S

#38 feat: switch to google cloud builder
  .prow.yaml
  Makefile
  README.md
  athenacli/Makefile
  athenacli/cloudbuild-build.yaml
  athenacli/cloudbuild-push.yaml
  dind/Makefile
  dind/cloudbuild-build.yaml
  dind/cloudbuild-push.yaml
  git-secret-scanner/Makefile
  git-secret-scanner/cloudbuild-build.yaml
  git-secret-scanner/cloudbuild-push.yaml
  go-builder/Makefile
  go-builder/cloudbuild-build.yaml
  go-builder/cloudbuild-push.yaml
  helm/Makefile
  helm/cloudbuild-build.yaml
  helm/cloudbuild-push.yaml
  kube-dind/Makefile
  kube-dind/cloudbuild-build.yaml
  kube-dind/cloudbuild-push.yaml
  python-builder/Makefile
  python-builder/cloudbuild-build.yaml
  python-builder/cloudbuild-push.yaml
  toolbox/Makefile
  toolbox/cloudbuild-build.yaml
  toolbox/cloudbuild-push.yaml
Labels: approved, lgtm, size/XL

#39 feat: install kubeval in toolbox
  toolbox/Dockerfile
  toolbox/Makefile
  toolbox/cloudbuild-build.yaml
  toolbox/cloudbuild-push.yaml
Labels: approved, lgtm, size/S

#40 feat: use newest python version and add g++
  python-builder/Dockerfile
  python-builder/Makefile
Labels: approved, lgtm, size/XS

#41 feat: bump tf in toolbox to 0.12.23
  toolbox/Makefile
Labels: approved, lgtm, size/XS

#42 feat: google cloud builder
  .prow.yaml
  Makefile
  gcloud-builder/Dockerfile
  gcloud-builder/Makefile
  gcloud-builder/cloudbuild-build.yaml
  gcloud-builder/cloudbuild-push.yaml
Labels: approved, lgtm, size/L
